### ISSUE TITLE
EML export stopped working (v2.0.0 b5)

### ISSUE THREAD

**Issue by vensko** [vladimiry/email-securely-app#68] opened 2018-11-15 19:15 UTC
This message started to show up after the Export command (native one):
![securely](https://user-images.githubusercontent.com/1040510/48575721-f8f09680-e912-11e8-9d58-b9738f000521.png)

It worked before, so I guess something changed on ProtonMail's side.

**Comment by vensko** [comment] 2018-11-15 21:30
This one:
![securely2](https://user-images.githubusercontent.com/1040510/48582902-1418d180-e926-11e8-9477-cf848e3b04d4.png)

**Comment by vladimiry** [comment] 2018-11-15 21:43
- Does the error occur on all the emails, or only on some of them?
- Does it work if you export the same message using Google Chrome browser but not this desktop app? This desktop app doesn't affect the Protonmail's export logic (is not supposed to), which means at first glance this issue looks like Protonmail's issue occurring on some emails.
- Does the app [built-in export](https://user-images.githubusercontent.com/1560781/47685893-64cfc100-dbe9-11e8-9cd7-56fad8d53055.gif) work for you, the one I pointed to in my previous message?

**Comment by vensko** [comment] 2018-11-15 23:36
- On most of them, without any obvious criteria. Encoding is hardly the reason. It rarely occurs with short emails.
- It works on the same messages in Chromium 67 and Firefox.

**Built-in export:**
- Tutanota produces garbled output in a very weird way:
![tutanota](https://user-images.githubusercontent.com/1040510/48588433-67475000-e937-11e8-9783-bf9b0dc39554.png)
- ProtonMail throws "Cannot read property 'Labels' of undefined" error popup (I have no labels) and then gets stuck on "Data loading ...".

**Comment by vladimiry** [comment] 2018-11-16 05:21
> On most of them, without any obvious criteria. Don't see any correlation with encoding. It rarely occurs on short emails. Always occurs on emails from Twitter.
> It works without errors on the same messages in Chromium 67 and Firefox.

So it works on the same system in browsers, but not inside the Electron container. Let's try to narrow down the scope. Can you call the Protonmail's export using this version https://github.com/vladimiry/email-securely-app/releases/tag/v1.5.0 (it's built with Electron v2 while the recent releases built with Electron v3) and if it still fails then also using this version https://github.com/vladimiry/email-securely-app/releases/tag/v0.3.1 (built with Electron v1)? It's better to rename your currently used settings directory for a while before starting experimenting, so it would be a fresh app start and experiments would not affect your primary settings.

> Built-in export

This looks weird and so far it's not reproducible on Linux on the same message. Besides I've never seen before that issues like you described were happing on Windows, not sure about macOS. Ideally I'm abe to reproduce the issue, so more information is needed:
- Direct link to the installation package file from the [releases](https://github.com/vladimiry/email-securely-app/releases) page you experience the described issues with.
- Operation system name and version.

> ProtonMail throws "Cannot read property 'Labels' of undefined" error popup (I have no labels) and then gets stuck on "Data loading ...".

App is supposed to handle "no labels" case flawlessly, can you perform the following steps?
- Make sure you are using the latest beta, currenlty it's [v2.0.0-beta.5](https://github.com/vladimiry/email-securely-app/releases/tag/v2.0.0-beta.5).
- Exit the app.
- Remove the `database.bin` file from the settings directory if it's there (same folder where `config.json` and `settings.bin` are located).
- Start the app and make sure "local store" is enabled.
- If the same `Cannot read property 'Labels' of undefined` error still occurs there should be respective error record in the `log.log` file localted in the settings directory. Would be great you share that error record if it's there.

Tutanota view:
![view-0](https://user-images.githubusercontent.com/1560781/48598032-f1aca580-e971-11e8-8a64-1d44ee284aec.png)
Offline view:
![view-1](https://user-images.githubusercontent.com/1560781/48598034-f1aca580-e971-11e8-842a-1761bd0ed28f.png)
Mail client view (exported the messages using app built-in EML export and then imported to Thunderbird):
![view-3](https://user-images.githubusercontent.com/1560781/48598035-f2453c00-e971-11e8-801f-2efd13f591bd.png)

**Comment by vensko** [comment] 2018-11-16 17:52
Ok, I managed to break export in Chromium and Firefox on relatively long emails. It has something to do with letter length, only in Electron this threshold appears to be much shorter than in normal browsers. I'll contact ProtonMail then.

I am on Windows 10 Pro 1079, and use this version https://github.com/vladimiry/email-securely-app/releases/download/v2.0.0-beta.5/email-securely-app-2.0.0-beta.5-windows-nsis-installer.exe

Log output fro ProtonMail:
```
[2018-11-16 18:48:56.686] [error] [WEB] [reducers/errors] <[account.component][0]> { message: 'Cannot read property \'Labels\' of undefined',
  name: 'TypeError' }
```

**Comment by vladimiry** [comment] 2018-11-17 08:39
> Ok, I managed to break export in Chromium and Firefox on relatively long emails. It has something to do with letter length, only in Electron this threshold appears to be much shorter than in normal browsers. I'll contact ProtonMail then.

> Export worked ok, and as for garbled output, it was EML viewer plugin for Total Commander, which apparently does not fully support the format. Thunderbird and Gmail indeed render them correctly.

So I'm closing this issue as resolved.

**Closed by vladimiry** 2018-11-17 08:39 UTC

**Comment by vensko** [comment] 2018-11-17 15:35
Btw, the original issue got resolved with today's update of ProtonMail's web app.
