### ISSUE TITLE
Desktop notifications do not work for ProtonMail

### ISSUE THREAD

**Issue by bartonhodges** [vladimiry/email-securely-app#58] opened 2018-10-23 13:07 UTC

**Comment by vladimiry** [comment] 2018-10-23 13:50
More details are needed:
- Operation system name and exact version.
- Application version.
- Recent log lines form your `log.log` file which is located in the settings folder. Logging needs to be switched to the `debug` level, see [here](https://github.com/vladimiry/email-securely-app/releases/tag/v1.3.0) how change the log level value. You can find email address for log file sending [here](https://github.com/vladimiry/email-securely-app/blob/master/package.json) (locate `author` property).

**Comment by bartonhodges** [comment] 2018-10-23 16:01
Operation system name and exact version: 
Windows 10 Professional Version 1803 OS Build 17134.345

Application version:
1.5.2

Did you try the app with Tutanota?
No

Does the desktop notification work for other applications? Also please make sure you have not disabled the notifications for this specific application on the operating system level.
Yes, it works when logging into ProtonMail with the Chrome browser.

**Comment by joshirio** [comment] 2018-10-23 16:39
Just a note, Notifications on Windows 10 1809 Professional x64 work for me, I remember it also being fine before upgrading to 1809 from 1803.

**Comment by vladimiry** [comment] 2018-10-23 17:54
@bartonhodges can you try https://github.com/vladimiry/email-securely-app/releases/tag/v1.5.0? That version comes with Electron v2. So if it works we could then relate the issue to Electron v3 upgrade.

**Comment by vladimiry** [comment] 2018-10-23 18:16
@bartonhodges did you install the app using `*-nsis-installer.exe` package and do you run the app via the created shortcut? Asking since running portable version might be a reason for not working notifications on Win 8-10, as the system requires proper shortcut to be created.

**Comment by bartonhodges** [comment] 2018-10-24 15:33
@vladimiry that was the problem, thanks!  I was running the portable version.  Installing it using the nsis installer allows desktop notifications when new emails arrive.  However, testing notifications using the "Test notification" link under settings still doesn't work.

**Comment by vladimiry** [comment] 2018-10-24 15:45
>  However, testing notifications using the "Test notification" link under settings still doesn't work.

It's by design. Ie it's supposed to be like that since app intentionally disables the [Tutanota](https://github.com/vladimiry/email-securely-app/blob/fe814ea8215d6feac1f120bae116129cb79378d6/src/electron-preload/webview/tutanota/index.ts#L30)/[Protonmail](https://github.com/vladimiry/email-securely-app/blob/fe814ea8215d6feac1f120bae116129cb79378d6/src/electron-preload/webview/protonmail/index.ts#L58) notifications in order to prevent possible confusion of showing notifications by the app and by Tutanota/Protonmailatn the same time.

So if the issue got fixed for you please close it.

**Closed** 2018-10-24 16:02 UTC

**Comment by vladimiry** [comment] 2018-10-24 16:19
I'm going to disable shipping portable builds within https://github.com/vladimiry/email-securely-app/issues/60.
