### ISSUE TITLE
[Bug] email doesn't unlock

### ISSUE THREAD

**Issue by jeroen7s** [vladimiry/email-securely-app#37] opened 2018-07-23 08:08 UTC
i've noticed that sometimes some of my emails don't unlock after starting the program
on first glance it seems like this happens mainly on tutanota emails
EDIT: seems like it's also happening on protonmail sometimes, sometimes it gets stuck on the 2FA
not sure what is causing this
![screenshot from 2018-07-23 10-05-36](https://user-images.githubusercontent.com/10954827/43064834-538af4ae-8e60-11e8-9b2d-b70d933af7a9.png)

**Comment by vladimiry** [comment] 2018-07-23 11:00
Tutanota support got added just about two weeks ago with [v1.0.0](https://github.com/vladimiry/email-securely-app/releases/tag/v1.0.0), while Protonmail is supported from the day one. So there definitely remain things to improve.

One of the reasons for adding [logged-in state indication](https://github.com/vladimiry/email-securely-app/releases/tag/v1.1.0) feature was in enabling a clear highlighting that something went wrong with auto-login process. Auto-login feature might get broken for example if the email provider changes its web UI, since app interacts with it resolving elements on the page by ankers hardcoded in the code (CSS selectors). But this issue doesn't seem to be about this case since for you it doesn't work sometimes, not always, which makes it even harder to detect a pattern.

I tweak the mail providers injection code time to time and so hopefully auto-login feature for Tutanota will be improved over time.

**Comment by jeroen7s** [comment] 2018-07-23 14:57
not sure if it helps but it seems like it's usually only the one that is in focus that fails to load
even if i don't click anywhere/type anything.

**Comment by joshirio** [comment] 2018-07-24 09:31
I can confirm this. I have this issue since the app was renamed to email-securely-app. I have 3 **protonmail** accounts and on the first start after a fresh boot (linux, KDE) one of the login gets stuck. After a restart of the app it always works on the second time.

Maybe the UI is too slow (web loading) and the app tries to login before the form is ready? This is my guess, because on the second start the app loads much faster since it is not a cold boot.

**Comment by vladimiry** [comment] 2018-07-24 09:36
I initially thought it's only about Tutanota, but it's not, thanks for giving more details.

**Comment by joshirio** [comment] 2018-07-26 07:07
I noticed that it is possible to reproduce this while downloading something (maxing out the download bandwidth). Looks like it happens more likely on slow internet connections.

**Comment by vladimiry** [comment] 2018-07-26 07:40
I've significantly enhanced a logging feature and looks like noticed a pattern. If the guess is correct, then a reliable fix is coming shortly.

Btw it's now will be possible to change app log level in app settings, with defaults to `error` level:

![log level select](https://user-images.githubusercontent.com/1560781/43248251-f0b47906-90bf-11e8-8838-5f4f62970ceb.png)

**Comment by vladimiry** [comment] 2018-07-27 00:51
Auto-login stability has been improved with [v1.3.0](https://github.com/vladimiry/email-securely-app/releases/tag/v1.3.0) pre-release. Let's keep issue opened for a while. Then in case of no new reports will turn release to stable an close.

**Comment by jeroen7s** [comment] 2018-07-27 10:00
looks good
did some basic testing (quitting the app, restarting the app, starting the app after rebooting...) and it seems to be reliable now, restarted the app about 15 times and the issue hasn't occurred once
:+1: from me

**Comment by vladimiry** [comment] 2018-07-27 10:04
Great, so fix is reliable. Keeping issue opened for a few days awaiting more possible feedbacks.

**Comment by vladimiry** [comment] 2018-07-30 14:58
Closing as resolved.

**Closed by vladimiry** 2018-07-30 14:58 UTC
Labels: bug
