### ISSUE TITLE
Removing accounts makes the settings dialog unclosable

### ISSUE THREAD

**Issue by ajgraves** [vladimiry/email-securely-app#99] opened 2019-01-26 02:47 UTC
When you remove an account, the settings dialog cannot be closed. Also, if you go to remove another account in this state, the remove button is grayed out with a spinning wheel in it (as if it were still processing the last removal). The only way to proceed is to force close the app.

**Comment by vladimiry** [comment] 2019-01-26 07:04
Thanks for the report. I managed to reproduce the issue somehow but the full pattern is not clear yet.

Some observations I've made so far:
- It only occurs under specific circumstances. For example when the concurrent accounts state update is happening. Which means it's more likely to happen when there are more than one account added and state of some of them is being updated too in the background.
- Actual account removing from encrypted `settings.bin` file always completes successfully in the background process. It's the app state in the renderer process like "removing in progress" is not being updated after the removing in the background process happened. That's why form remains locked with spinning wheel icon displayed.

**Comment by vladimiry** [comment] 2019-01-26 14:17
Here is the updated progress. The issue occurs for any account that has local store option enabled and that is in a logged-in state (think as local store option got activated). Even if that's a single account in the app and even if there is no concurrent accounts state updating happening. This observation significantly narrows down the scope.

**Comment by ajgraves** [comment] 2019-01-26 16:02
Sorry, I forgot to include the fact that local storage was enabled. Glad you’re narrowing it down.

**Comment by vladimiry** [comment] 2019-01-26 19:13
Fix is on the way.

**Comment by vladimiry** [comment] 2019-01-26 20:32
Version with the fix included uploaded [here](https://www.dropbox.com/sh/y413x6c06tt7kbf/AAAtO3tsjsnH40EHVMHpVmy_a?dl=0&lst=). Can you try it and confirm that issue is gone? I will publish new release in about a week since I'm going to wait a little more for [this](https://github.com/vladimiry/email-securely-app/issues/93) issue validation period expiration.

**Comment by ajgraves** [comment] 2019-01-27 02:56
This seems to be fixed. Great job!

**Comment by vladimiry** [comment] 2019-02-03 10:20
Fix has been released with [v2.3.0](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.0).

**Closed by vladimiry** 2019-02-03 10:20 UTC
Labels: bug
